[[redirects]]
  from = "/*"
  to = "/dist/static/ar/:splat"
  status = 200
  force = true
  conditions = { Host = ["ar.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/cl/:splat"
  status = 200
  force = true
  conditions = { Host = ["cl.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/bo/:splat"
  status = 200
  force = true
  conditions = { Host = ["bo.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/br/:splat"
  status = 200
  force = true
  conditions = { Host = ["br.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/mx/:splat"
  status = 200
  force = true
  conditions = { Host = ["mx.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/uy/:splat"
  status = 200
  force = true
  conditions = { Host = ["uy.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/dist/static/ve/:splat"
  status = 200
  force = true
  conditions = { Host = ["ve.gh.dolarapi.com"] }
