[[redirects]]
  from = "/*"
  to = "/ar/:splat"
  status = 200
  force = true
  conditions = { Host = ["ar.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/cl/:splat"
  status = 200
  force = true
  conditions = { Host = ["cl.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/bo/:splat"
  status = 200
  force = true
  conditions = { Host = ["bo.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/br/:splat"
  status = 200
  force = true
  conditions = { Host = ["br.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/mx/:splat"
  status = 200
  force = true
  conditions = { Host = ["mx.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/uy/:splat"
  status = 200
  force = true
  conditions = { Host = ["uy.gh.dolarapi.com"] }

[[redirects]]
  from = "/*"
  to = "/ve/:splat"
  status = 200
  force = true
  conditions = { Host = ["ve.gh.dolarapi.com"] }
